name: Wild
main: SkyLightMCPE\Main
version: 1.0.0
api: [3.0.0-ALPHA11, 3.0.0-ALPAH12]
author: 
- SkyLightMCPE
- Unickorn
website: https://github.com/SkyLightMCPE
commands:
 wild:
  usage: /wild 
  description: Teleports you in a random place!
